### ISSUE TITLE
Output directory permissions

### ISSUE THREAD

**Issue by AronHetLam** [actions/jekyll-build-pages#101]
Hi

I ran into an issue with permissions on the generated output folder.
The jekyll build output is as expected, but the `download-artifact` step fails due to missing permissions.
I tried adding `- run: mkdir -p ./output/publish` in between the two steps, but that fails due to missing permissions as well.

``` yml
...
      - uses: actions/jekyll-build-pages@v1
        with:
          destination: ./output
      - uses: actions/download-artifact@v3
        with:
          path: ./output/publish
...
```

The workaround i have now is adding `- run: mkdir ./output` before the jekyll build step, which makes it have the necessary permissions.
