### ISSUE TITLE
How to configure _config.yml file?

### ISSUE THREAD

**Issue by kamontat** [actions/jekyll-build-pages#53]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/c/code-to-cloud/github-actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by vadimkantorov** [comment]
@yoannchaudet In particular, I have `data_dir`, `layouts_dir` and `includes_dir` options set in my `_config.yml`, but they seem not taken into account. Maybe related to https://github.com/actions/jekyll-build-pages/issues/34?

**Comment by yoannchaudet** [comment]
Hope it helps: http://jekyllrb.com/docs/configuration/

**Comment by kamontat** [comment]
@yoannchaudet Let me re-phase the question.
My Github Action look like below
```yml
      - name: Building Jekyll output
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./_docs
          destination: ./_site
```
So I try to add `_config.yml` on **./_docs** however, it didn't load correctly. Put `_config.yml` on root is not a option as well because we develop monorepo and root are reserve for globally use config.

My idea is add another **with** for provide directory to _config.yml? What do you think

```yml
      - name: Building Jekyll output
        uses: actions/jekyll-build-pages@v1
        with:
          config: ./_docs/_config.yml
          source: ./_docs
          destination: ./_site
```
