### ISSUE TITLE
Followup question #53

### ISSUE THREAD

**Issue by kamontat** [actions/jekyll-build-pages#55]
@yoannchaudet Let me re-phase the question.

My Github Action look like below
```yml
      - name: Building Jekyll output
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./_docs
          destination: ./_site
```
So I try to add `_config.yml` on **./_docs** however, it didn't load correctly. Put `_config.yml` on root is not a option as well because we develop monorepo and root are reserve for globally use config.

My idea is add another **with** for provide directory to _config.yml? What do you think

```yml
      - name: Building Jekyll output
        uses: actions/jekyll-build-pages@v1
        with:
          config: ./_docs/_config.yml
          source: ./_docs
          destination: ./_site
```

_Originally posted by @kamontat in https://github.com/actions/jekyll-build-pages/issues/53#issuecomment-1321419559_
