### ISSUE TITLE
Use with Corporate Registry

### ISSUE THREAD

**Issue by syradar** [actions/jekyll-build-pages#57]
Hi would it be possible to change the image URL or make it configurable so that we could use it with our own registry?
Our runners are not allowed to access the internet but we have an internal artifactory where we could pull the image from.

```yml
runs:
  using: 'docker'
  image: 'docker://ghcr.io/actions/jekyll-build-pages:v1.0.6'
```

Or would it be easier to just fork it?
